name: build
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3
      - run: pip install build
      - run: python -m build .
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
